<a href="https://colab.research.google.com/github/Arj05/My_files/blob/master/LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install sklearn

In [0]:
from sklearn.linear_model  import LinearRegression

In [0]:
from sklearn.datasets import load_iris
dataset= load_iris()


In [0]:
type(dataset)

sklearn.utils.Bunch

In [0]:
dataset.target[[10, 25, 50]]                                                                                                                          

array([0, 0, 1])

In [0]:
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [0]:
import numpy as np
np.unique(dataset.target)

array([0, 1, 2])

In [0]:
# STEP -1 

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(dataset.data, dataset.target, train_size=0.7, random_state=1999, stratify=dataset.target)

In [0]:
x_train.shape

(105, 4)

In [0]:
y_train.shape

(105,)

In [0]:
x_test.shape

(45, 4)

In [0]:
y_test.shape

(45,)

In [0]:
# STEP- 2

classifier = LinearRegression()



In [0]:
# STEP - 3   Training on x_train, y_train

classifier.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
# STEP-4 


predictions = classifier.predict(x_test)     # values that have been by the classifier, y_test are the true values

In [0]:
predictions.shape

(45,)

In [0]:


classifier.score(x_test, y_test)             

0.9292185691933678

In [0]:
predictions

array([ 1.18396691,  1.11719516, -0.01598656,  1.75034435,  1.17449591,
       -0.04179144,  0.23344403,  0.15326344,  2.23681073,  1.28090966,
        1.57306316,  1.71331405,  1.89495901,  1.74683497,  1.07856595,
       -0.06089163,  1.19184205, -0.0138044 ,  1.47670582,  1.17391086,
       -0.13202969,  1.28543182,  1.73342685,  1.72672181,  1.28543201,
        1.34608412,  2.18886729,  1.13017553, -0.00316295,  2.05298198,
        1.6627169 ,  1.15145842, -0.06759614,  1.83941232,  0.00646553,
        0.95464877, -0.07488515,  1.20131322,  0.19087842,  0.0456787 ,
        0.01200066,  1.98897708,  0.02322662,  1.39972018,  1.59769849])

In [0]:
y_test

array([1, 1, 0, 2, 1, 0, 0, 0, 2, 1, 2, 2, 2, 2, 1, 0, 1, 0, 2, 1, 0, 1,
       2, 2, 1, 1, 2, 1, 0, 2, 2, 1, 0, 2, 0, 1, 0, 1, 0, 0, 0, 2, 0, 1,
       2])

In [0]:
[[1,2,3], [3, 4, 5]]

[[1, 2, 3], [3, 4, 5]]

In [0]:
####  1% of the entire work, 99% preprocessing 